"""
================================================================================
Simulation-Informed Deep Learning for Estimating Material Parameters from Microstructural Morphology

Authors     : Asfandyar Khan, Amir Abbas Kazemzadeh Farizhandi, Mahmood Mamivand
Affiliation : Micron School of Materials Science and Engineering, Boise State University

Description
-----------
Trains a multi-task CNN regression model to infer the gradient energy
coefficient and effective mobility from 2D grayscale microstructure
images generated by a Cahn-Hilliard phase-field model of Fe-Cr spinodal
decomposition at 500 C (773 K).

Pipeline
--------
1.  Load labeled dataset (image, kappa, M) from CSV
2.  Extract features using a frozen EfficientNetB7 backbone truncated at layer 464
3.  Apply Global Average Pooling + Global Max Pooling, concatenate (2688-d vector)
4.  Stratified 70/10/20 train/validation/test split
5.  Standardize features using training-set statistics only (no leakage)
6.  Train multi-task regression head for kappa and M
7.  Evaluate on held-out test set (R2, MAE, parity plots)
8.  Test generalization on off-grid (interpolation) dataset
9.  Predict kappa and M for an experimental HAADF-STEM image

Reproducibility
---------------
Global seed : 42
Split seed  : 42
TensorFlow deterministic ops enabled where available
================================================================================
"""

# ==============================================================================
# SECTION 0 — REPRODUCIBILITY
# Must be set before any other imports so environment variables take effect.
# ==============================================================================

import os

SEED = 42

os.environ["PYTHONHASHSEED"]         = str(SEED)
os.environ["TF_DETERMINISTIC_OPS"]   = "1"
os.environ["TF_CUDNN_DETERMINISTIC"] = "1"
os.environ["NVIDIA_TF32_OVERRIDE"]   = "0"
os.environ["OMP_NUM_THREADS"]        = "1"
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"


# ==============================================================================
# SECTION 1 — IMPORTS
# ==============================================================================

import sys
import time
import pickle

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import tensorflow as tf

tf.keras.utils.set_random_seed(SEED)

try:
    tf.config.experimental.enable_op_determinism(True)
except Exception:
    print("[WARN] Determinism flag not available in this TF version.")

tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(1)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Dense, BatchNormalization, Dropout, Activation, Input,
    GlobalAveragePooling2D, GlobalMaxPooling2D, Concatenate
)
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.applications import EfficientNetB7, imagenet_utils
from tensorflow.keras.preprocessing.image import load_img, img_to_array

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity


# ==============================================================================
# SECTION 2 — CONFIGURATION
# ==============================================================================

# --- Paths ---
BASE   = "/path/to/images"  # directory containing all image files and data.csv

CSV_PATH = os.path.join(BASE, "data.csv") # CSV must have columns: image_name, kappa, mob

SAVE_DIR = "/path/to/save/results"  # directory to save model weights, figures, and CSVs

EXP_PATH = "/path/to/experimental/image.png" # path to experimental image for prediction 

# Off-grid interpolation test paths
INTERP_DIR = "/path/to/interpolation/images" # directory containing off-grid images and data.csv with true kappa and mob values for evaluation
INTERP_CSV = os.path.join(INTERP_DIR, "data.csv") # CSV must have columns: image_name, kappa, mob

os.makedirs(SAVE_DIR, exist_ok=True)

# --- Model ---
LAYER    = 464          # EfficientNetB7 feature extraction layer index
IMG_SIZE = (600, 600)   # input resolution for EfficientNetB7

# --- Training ---
EPOCHS      = 600
BATCH       = 8
LR          = 1e-3
DELTA_K     = 2.0       # Huber loss delta for kappa
DELTA_M     = 2.0       # Huber loss delta for mobility
WEIGHT_K    = 0.8       # loss weight for kappa
WEIGHT_M    = 1.2       # loss weight for mobility
DROPOUT     = 0.1       # dropout rate in regression head
ES_PATIENCE = 100       # early stopping patience (epochs)
LR_PATIENCE = 20        # ReduceLROnPlateau patience
LR_FACTOR   = 0.80      # LR reduction factor per plateau
LR_MIN      = 1e-5      # minimum learning rate floor

# --- Dataset split ---
TRAIN_FRAC = 0.70
VAL_FRAC   = 0.10
TEST_FRAC  = 0.20
N_BINS     = 6          # quantile bins for stratified split


# ==============================================================================
# SECTION 3 — UTILITY FUNCTIONS
# ==============================================================================

def load_dataset(csv_path):
    """Load image filenames and labels (kappa, mobility) from CSV."""
    df = pd.read_csv(csv_path, header=None, names=["image_name", "kappa", "mob"])
    print(f"[INFO] Dataset loaded: {df.shape[0]} samples")
    return df


def pool_features(feats):
    """
    Apply Global Average Pooling (GAP) and Global Max Pooling (GMP) to an
    intermediate feature map and concatenate the results.

    Used identically for training and experimental images to ensure consistent
    feature representation across all inputs.

    Parameters
    ----------
    feats : np.ndarray, shape (N, H, W, C)
        Feature map output from EfficientNetB7 truncated at LAYER.

    Returns
    -------
    np.ndarray, shape (N, 2*C)
        Concatenated GAP + GMP vector. For layer 464: shape (N, 2688).
    """
    feats_tensor = tf.convert_to_tensor(feats)
    gap = GlobalAveragePooling2D()(feats_tensor)
    gmp = GlobalMaxPooling2D()(feats_tensor)
    return Concatenate()([gap, gmp]).numpy()


def extract_features(df, image_dir, pre_model, img_size):
    """
    Load and preprocess images, extract intermediate features from the
    EfficientNetB7 backbone, then apply GAP + GMP pooling.

    Parameters
    ----------
    df         : pd.DataFrame   — must contain 'image_name' column
    image_dir  : str            — directory containing image files
    pre_model  : keras.Model    — EfficientNetB7 truncated at LAYER
    img_size   : tuple          — target image size, e.g. (600, 600)

    Returns
    -------
    np.ndarray, shape (N, 2688)
    """
    images = []
    for img_name in df["image_name"]:
        path  = os.path.join(image_dir, img_name)
        image = load_img(path, target_size=img_size)
        image = img_to_array(image)
        image = np.expand_dims(image, axis=0)
        image = imagenet_utils.preprocess_input(image)
        images.append(image)

    x = np.vstack(images)
    print("[INFO] Extracting CNN features...")
    feats = pre_model.predict(x, batch_size=32)
    print(f"[INFO] Raw feature map shape : {feats.shape}")

    feats_flat = pool_features(feats)
    print(f"[INFO] After GAP + GMP       : {feats_flat.shape}")
    return feats_flat


def stratified_split(df, features, val_frac, test_frac, seed, n_bins):
    """
    Stratified three-way split (train / val / test).

    Both kappa and mobility are jointly binned into quantile intervals and the
    combined bin label is used as the stratification variable, ensuring balanced
    parameter-space coverage across all three sets.

    Parameters
    ----------
    df        : pd.DataFrame
    features  : np.ndarray
    val_frac  : float   — fraction of full dataset for validation
    test_frac : float   — fraction of full dataset for test
    seed      : int
    n_bins    : int     — number of quantile bins per parameter

    Returns
    -------
    train_df, val_df, test_df, trainX, valX, testX
    """
    kbin   = pd.qcut(df["kappa"], q=n_bins, duplicates="drop")
    mbin   = pd.qcut(df["mob"],   q=n_bins, duplicates="drop")
    strata = (kbin.astype(str) + "_" + mbin.astype(str)).astype(str)

    trainval_idx, test_idx = train_test_split(
        np.arange(len(df)),
        test_size    = test_frac,
        random_state = seed,
        stratify     = strata
    )

    adjusted_val = val_frac / (1.0 - test_frac)
    train_idx, val_idx = train_test_split(
        trainval_idx,
        test_size    = adjusted_val,
        random_state = seed,
        stratify     = strata.iloc[trainval_idx].values
    )

    print(f"[INFO] Split — train: {len(train_idx)} | "
          f"val: {len(val_idx)} | test: {len(test_idx)}")

    return (
        df.iloc[train_idx].reset_index(drop=True),
        df.iloc[val_idx].reset_index(drop=True),
        df.iloc[test_idx].reset_index(drop=True),
        features[train_idx],
        features[val_idx],
        features[test_idx]
    )


def compute_similarity_metrics(df, features, save_dir, layer):
    """
    Compute pairwise cosine similarity across the full dataset.

    Used for diagnostic purposes only — not used during training and does
    not affect model evaluation. Computes max similarity, mean similarity,
    and uniqueness (1 - max_sim) per image.

    Returns pd.DataFrame with columns: image_name, max_sim, mean_sim, uniqueness.
    """
    print("[INFO] Computing cosine similarity (full dataset)...")
    sim_matrix = cosine_similarity(features)
    np.fill_diagonal(sim_matrix, 0.0)

    sim_df = pd.DataFrame({
        "image_name" : df["image_name"].values,
        "max_sim"    : sim_matrix.max(axis=1),
        "mean_sim"   : sim_matrix.sum(axis=1) / (len(df) - 1),
        "uniqueness" : 1.0 - sim_matrix.max(axis=1)
    })

    out = os.path.join(save_dir, f"similarity_metrics_{layer}.csv")
    sim_df.to_csv(out, index=False)
    print(f"[INFO] Similarity metrics saved: {out}")
    return sim_df


def parity_plot(gt, pred, minv, maxv, title, outname):
    """Save a parity (predicted vs ground truth) scatter plot to disk."""
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.scatter(gt, pred, alpha=0.7, edgecolors="k", linewidths=0.4)
    ax.plot([minv, maxv], [minv, maxv], "r--", linewidth=1.2, label="Ideal (y = x)")
    ax.set_xlim(minv, maxv)
    ax.set_ylim(minv, maxv)
    ax.set_xlabel("Ground truth", fontsize=12)
    ax.set_ylabel("Prediction",   fontsize=12)
    ax.set_title(title,           fontsize=12)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(outname, dpi=300)
    plt.close(fig)


# ==============================================================================
# SECTION 4 — MODEL ARCHITECTURE
# ==============================================================================

def build_regression_head(input_dim):
    """
    Multi-task regression network.

    Architecture
    ------------
    Input (2688-d feature vector)
        Feature compression block
            Dense(512) → BatchNorm → Swish → Dropout(0.1)
            Dense(128) → BatchNorm → Swish
        Shared trunk
            Dense(256) → ReLU → Dropout(0.1)
            Dense(128) → ReLU
        Task-specific heads (one per output)
            Dense(64)  → ReLU → Dense(1, linear)

    Parameters
    ----------
    input_dim : int
        Dimensionality of the pooled feature vector (2688 for layer 464).

    Returns
    -------
    keras.Model with outputs [kappa, mob]
    """
    inp = Input(shape=(input_dim,))

    # feature compression block
    x = Dense(512)(inp)
    x = BatchNormalization()(x)
    x = Activation("swish")(x)
    x = Dropout(DROPOUT)(x)
    x = Dense(128)(x)
    x = BatchNormalization()(x)
    x = Activation("swish")(x)

    # shared trunk
    x = Dense(256, activation="relu")(x)
    x = Dropout(DROPOUT)(x)
    x = Dense(128, activation="relu")(x)

    # task-specific heads
    kappa_out = Dense(64, activation="relu")(x)
    kappa_out = Dense(1, activation="linear", name="kappa")(kappa_out)

    mob_out = Dense(64, activation="relu")(x)
    mob_out = Dense(1, activation="linear", name="mob")(mob_out)

    return Model(inputs=inp, outputs=[kappa_out, mob_out])


# ==============================================================================
# SECTION 5 — MAIN SCRIPT
# ==============================================================================

if __name__ == "__main__":

    t_start = time.time()

    print("=" * 70)
    print("  Fe-Cr CNN Inverse Parameter Estimation")
    print("=" * 70)
    print(f"  GPU        : {tf.config.list_physical_devices('GPU')}")
    print(f"  Python     : {sys.version.split()[0]}")
    print(f"  TensorFlow : {tf.__version__}")
    print(f"  Seed       : {SEED}")
    print("=" * 70)

    # ------------------------------------------------------------------
    # 5.1  Load dataset
    # ------------------------------------------------------------------
    df = load_dataset(CSV_PATH)

    # ------------------------------------------------------------------
    # 5.2  Build EfficientNetB7 feature extractor (frozen)
    # ------------------------------------------------------------------
    print(f"[INFO] Loading EfficientNetB7 truncated at layer {LAYER}...")
    backbone  = EfficientNetB7(weights="imagenet", include_top=False)
    pre_model = Model(
        inputs  = backbone.inputs,
        outputs = backbone.layers[LAYER].output
    )

    # ------------------------------------------------------------------
    # 5.3  Extract features for all images
    # ------------------------------------------------------------------
    features = extract_features(df, BASE, pre_model, IMG_SIZE)

    # ------------------------------------------------------------------
    # 5.4  Dataset-level similarity diagnostics (pre-split, diagnostic only)
    # ------------------------------------------------------------------
    sim_df = compute_similarity_metrics(df, features, SAVE_DIR, LAYER)

    # ------------------------------------------------------------------
    # 5.5  Stratified train / val / test split
    # ------------------------------------------------------------------
    train_df, val_df, test_df, trainX_raw, valX_raw, testX_raw = stratified_split(
        df, features,
        val_frac  = VAL_FRAC,
        test_frac = TEST_FRAC,
        seed      = SEED,
        n_bins    = N_BINS
    )

    # ------------------------------------------------------------------
    # 5.6  Feature standardization — fit on train only to prevent leakage
    # ------------------------------------------------------------------
    scaler = StandardScaler()
    trainX = scaler.fit_transform(trainX_raw)
    valX   = scaler.transform(valX_raw)
    testX  = scaler.transform(testX_raw)

    train_kappa = train_df["kappa"].values;  train_mob = train_df["mob"].values
    val_kappa   = val_df["kappa"].values;    val_mob   = val_df["mob"].values
    test_kappa  = test_df["kappa"].values;   test_mob  = test_df["mob"].values

    # ------------------------------------------------------------------
    # 5.7  Build and compile model
    # ------------------------------------------------------------------
    print("[INFO] Building regression model...")
    model = build_regression_head(trainX.shape[1])

    model.compile(
        optimizer    = tf.keras.optimizers.Adam(learning_rate=LR),
        loss         = {
            "kappa" : tf.keras.losses.Huber(delta=DELTA_K),
            "mob"   : tf.keras.losses.Huber(delta=DELTA_M)
        },
        loss_weights = {"kappa": WEIGHT_K, "mob": WEIGHT_M},
        metrics      = {"kappa": ["mae"], "mob": ["mae"]}
    )

    model.summary()

    # ------------------------------------------------------------------
    # 5.8  Callbacks
    # ------------------------------------------------------------------
    best_weights = os.path.join(SAVE_DIR, f"weights_best_layer{LAYER}.weights.h5")

    callbacks = [
        ModelCheckpoint(
            best_weights,
            monitor           = "val_loss",
            save_best_only    = True,
            save_weights_only = True,
            verbose           = 1
        ),
        ReduceLROnPlateau(
            monitor  = "val_loss",
            factor   = LR_FACTOR,
            patience = LR_PATIENCE,
            min_lr   = LR_MIN,
            verbose  = 1
        ),
        EarlyStopping(
            monitor              = "val_loss",
            patience             = ES_PATIENCE,
            min_delta            = 1e-10,
            restore_best_weights = False   # weights loaded explicitly after training
        )
    ]

    # ------------------------------------------------------------------
    # 5.9  Build tf.data pipelines
    # ------------------------------------------------------------------
    ds_train = (
        tf.data.Dataset
        .from_tensor_slices((trainX, {"kappa": train_kappa, "mob": train_mob}))
        .shuffle(buffer_size=len(trainX), seed=SEED, reshuffle_each_iteration=True)
        .batch(BATCH)
    )

    ds_val = (
        tf.data.Dataset
        .from_tensor_slices((valX, {"kappa": val_kappa, "mob": val_mob}))
        .batch(BATCH)
    )

    # ------------------------------------------------------------------
    # 5.10  Training
    # ------------------------------------------------------------------
    print(f"[INFO] Training — max {EPOCHS} epochs, "
          f"early stopping patience = {ES_PATIENCE}...")

    history = model.fit(
        ds_train,
        validation_data = ds_val,
        epochs          = EPOCHS,
        callbacks       = callbacks,
        verbose         = 1
    )

    # ------------------------------------------------------------------
    # 5.11  Save training history
    # ------------------------------------------------------------------
    train_loss = history.history["loss"]
    val_loss   = history.history["val_loss"]
    epochs_ran = range(1, len(train_loss) + 1)

    best_epoch = int(np.argmin(val_loss)) + 1
    best_val   = float(np.min(val_loss))

    print(f"\n── Training summary ──────────────────────────")
    print(f"   Epochs run       : {len(train_loss)}")
    print(f"   Best epoch       : {best_epoch}")
    print(f"   Best val loss    : {best_val:.6f}")
    print(f"   Final train loss : {train_loss[-1]:.6f}")
    print(f"   Final val loss   : {val_loss[-1]:.6f}")
    print(f"──────────────────────────────────────────────\n")

    # loss curve plot
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(epochs_ran, train_loss, color="#2171b5", linewidth=1.5, label="Training loss")
    ax.plot(epochs_ran, val_loss,   color="#e8471a", linewidth=1.5, linestyle="--", label="Validation loss")
    ax.axvline(x=best_epoch, color="#41ab5d", linewidth=1.2, linestyle=":",
               label=f"Best epoch ({best_epoch})")
    ax.scatter([best_epoch], [best_val], color="#41ab5d", zorder=5, s=50)
    ax.set_xlabel("Epoch",          fontsize=12)
    ax.set_ylabel("Loss (Huber)",   fontsize=12)
    ax.set_title(f"Training and Validation Loss  |  Layer {LAYER}", fontsize=13)
    ax.legend(fontsize=11)
    ax.grid(True, alpha=0.4)
    fig.tight_layout()
    fig.savefig(os.path.join(SAVE_DIR, f"loss_curve_layer{LAYER}.png"), dpi=300)
    plt.close(fig)

    # loss history CSV + pickle
    pd.DataFrame({
        "epoch"      : list(epochs_ran),
        "loss"       : train_loss,
        "val_loss"   : val_loss
    }).to_csv(os.path.join(SAVE_DIR, f"loss_history_layer{LAYER}.csv"), index=False)

    with open(os.path.join(SAVE_DIR, f"history_layer{LAYER}.pkl"), "wb") as f:
        pickle.dump(history.history, f)

    print("[INFO] Loss curve, CSV, and pickle saved.")

    # ------------------------------------------------------------------
    # 5.12  Evaluation on held-out test set
    # ------------------------------------------------------------------
    print("\n[INFO] Evaluating on held-out test set...")
    model.load_weights(best_weights)

    pred_kappa, pred_mob = model.predict(testX)
    pred_kappa = pred_kappa.flatten()
    pred_mob   = pred_mob.flatten()

    r2_k  = r2_score(test_kappa, pred_kappa)
    mse_k = mean_squared_error(test_kappa, pred_kappa)
    mae_k = mean_absolute_error(test_kappa, pred_kappa)

    r2_m  = r2_score(test_mob, pred_mob)
    mse_m = mean_squared_error(test_mob, pred_mob)
    mae_m = mean_absolute_error(test_mob, pred_mob)

    print(f"\n── Test set performance ──────────────────────")
    print(f"   Kappa    R²  : {r2_k:.4f}")
    print(f"   Kappa    MSE : {mse_k:.4f}")
    print(f"   Kappa    MAE : {mae_k:.4f}")
    print(f"   Mobility R²  : {r2_m:.4f}")
    print(f"   Mobility MSE : {mse_m:.4f}")
    print(f"   Mobility MAE : {mae_m:.4f}")
    print(f"──────────────────────────────────────────────\n")

    parity_plot(test_kappa, pred_kappa, 0, 11,
                f"kappa  |  R²={r2_k:.3f}",
                os.path.join(SAVE_DIR, f"parity_kappa_layer{LAYER}.png"))

    parity_plot(test_mob, pred_mob, 0, 11,
                f"Mobility  |  R²={r2_m:.3f}",
                os.path.join(SAVE_DIR, f"parity_mob_layer{LAYER}.png"))

    # ------------------------------------------------------------------
    # 5.13  Prediction error table
    # ------------------------------------------------------------------
    err_kappa = np.abs(test_kappa - pred_kappa)
    err_mob   = np.abs(test_mob   - pred_mob)

    error_df = pd.DataFrame({
        "image_name" : test_df["image_name"].values,
        "kappa_gt"   : test_kappa,
        "kappa_pred" : pred_kappa,
        "err_kappa"  : err_kappa,
        "mob_gt"     : test_mob,
        "mob_pred"   : pred_mob,
        "err_mob"    : err_mob,
        "err_total"  : err_kappa + err_mob
    })

    error_df.to_csv(os.path.join(SAVE_DIR, "prediction_errors.csv"), index=False)
    print("[INFO] Prediction errors saved.")

    for col, label in [("err_kappa", "kappa"), ("err_mob", "mobility"), ("err_total", "total")]:
        top = error_df.sort_values(col, ascending=False).head(10)
        print(f"\n── Top 10 worst {label} predictions ─────────")
        print(top[["image_name", col]].to_string(index=False))

    # ------------------------------------------------------------------
    # 5.14  Error vs similarity analysis
    # ------------------------------------------------------------------
    merged = error_df.merge(sim_df, on="image_name", how="left")
    merged.to_csv(
        os.path.join(SAVE_DIR, f"errors_with_similarity_layer{LAYER}.csv"),
        index=False
    )

    corr_uni = np.corrcoef(merged["err_total"], merged["uniqueness"])[0, 1]
    corr_sim = np.corrcoef(merged["err_total"], merged["max_sim"])[0, 1]
    print(f"\n── Error-similarity correlations ─────────────")
    print(f"   Corr(total error, uniqueness) : {corr_uni:.4f}")
    print(f"   Corr(total error, max_sim)    : {corr_sim:.4f}")
    print(f"──────────────────────────────────────────────\n")

    for x_col, xlabel, fname in [
        ("uniqueness", "Uniqueness (1 - max similarity)", "err_vs_uniqueness"),
        ("max_sim",    "Max cosine similarity",            "err_vs_maxsim")
    ]:
        fig, ax = plt.subplots()
        ax.scatter(merged[x_col], merged["err_total"], alpha=0.7)
        ax.set_xlabel(xlabel)
        ax.set_ylabel(r"Total absolute error ($|\Delta\kappa| + |\Delta M|$)")
        ax.grid(True, alpha=0.3)
        fig.tight_layout()
        fig.savefig(os.path.join(SAVE_DIR, f"{fname}_layer{LAYER}.png"), dpi=200)
        plt.close(fig)

    print("[INFO] Error-similarity plots saved.")

    # ------------------------------------------------------------------
    # 5.15  Experimental image prediction
    # ------------------------------------------------------------------
    print("\n[INFO] Predicting on experimental HAADF-STEM image...")
    print(f"       {EXP_PATH}")

    exp_img    = load_img(EXP_PATH, target_size=IMG_SIZE)
    exp_img    = imagenet_utils.preprocess_input(
                     np.expand_dims(img_to_array(exp_img), axis=0))
    exp_feats  = pre_model.predict(exp_img)
    exp_flat   = pool_features(exp_feats)         # same pooling as training
    exp_scaled = scaler.transform(exp_flat)        # same scaler as training

    pred_k_exp = float(model.predict(exp_scaled)[0].flatten()[0])
    pred_m_exp = float(model.predict(exp_scaled)[1].flatten()[0])

    print(f"\n── Experimental image prediction ─────────────")
    print(f"   Predicted kappa    : {pred_k_exp:.4f}  (x10^-16 J m^2 mol^-1)")
    print(f"   Predicted mobility : {pred_m_exp:.4f}  (x10^-26 m^2 mol J^-1 s^-1)")
    print(f"──────────────────────────────────────────────\n")

    out_txt = os.path.join(SAVE_DIR, "experimental_prediction.txt")
    with open(out_txt, "w") as f:
        f.write("Experimental Image Prediction\n")
        f.write("-" * 40 + "\n")
        f.write(f"Image path         : {EXP_PATH}\n")
        f.write(f"Predicted kappa    : {pred_k_exp:.6f}  (x10^-16 J m^2 mol^-1)\n")
        f.write(f"Predicted mobility : {pred_m_exp:.6f}  (x10^-26 m^2 mol J^-1 s^-1)\n")
    print(f"[INFO] Experimental prediction saved: {out_txt}")

    # ------------------------------------------------------------------
    # 5.16  Off-grid interpolation generalization test
    # ------------------------------------------------------------------
    print("\n" + "=" * 70)
    print("  OFF-GRID INTERPOLATION GENERALIZATION TEST")
    print("=" * 70)

    interp_df = load_dataset(INTERP_CSV)

    print(f"\n── Off-grid dataset summary ──────────────────")
    print(f"   Samples        : {len(interp_df)}")
    print(f"   Kappa range    : {interp_df['kappa'].min()} to {interp_df['kappa'].max()}")
    print(f"   Mobility range : {interp_df['mob'].min()} to {interp_df['mob'].max()}")
    print(f"──────────────────────────────────────────────\n")

    # feature extraction and standardization use the same pipeline as training
    interp_feats  = extract_features(interp_df, INTERP_DIR, pre_model, IMG_SIZE)
    interp_scaled = scaler.transform(interp_feats)   # transform only — never refit

    model.load_weights(best_weights)
    pred_k_interp, pred_m_interp = model.predict(interp_scaled)
    pred_k_interp = pred_k_interp.flatten()
    pred_m_interp = pred_m_interp.flatten()

    r2_k_interp  = r2_score(interp_df["kappa"].values, pred_k_interp)
    mae_k_interp = mean_absolute_error(interp_df["kappa"].values, pred_k_interp)
    mse_k_interp = mean_squared_error(interp_df["kappa"].values, pred_k_interp)

    r2_m_interp  = r2_score(interp_df["mob"].values, pred_m_interp)
    mae_m_interp = mean_absolute_error(interp_df["mob"].values, pred_m_interp)
    mse_m_interp = mean_squared_error(interp_df["mob"].values, pred_m_interp)

    print(f"\n── Off-grid test results ─────────────────────")
    print(f"   Kappa    R²  : {r2_k_interp:.4f}")
    print(f"   Kappa    MSE : {mse_k_interp:.4f}")
    print(f"   Kappa    MAE : {mae_k_interp:.4f}")
    print(f"   Mobility R²  : {r2_m_interp:.4f}")
    print(f"   Mobility MSE : {mse_m_interp:.4f}")
    print(f"   Mobility MAE : {mae_m_interp:.4f}")
    print(f"──────────────────────────────────────────────\n")

    print(f"\n── Grid test vs off-grid test comparison ─────")
    print(f"{'Metric':<25} {'Grid test':>15} {'Off-grid':>15}")
    print("-" * 57)
    for label, gv, ov in [
        ("Kappa R²",    r2_k,  r2_k_interp),
        ("Kappa MSE",   mse_k, mse_k_interp),
        ("Kappa MAE",   mae_k, mae_k_interp),
        ("Mobility R²", r2_m,  r2_m_interp),
        ("Mobility MSE",mse_m, mse_m_interp),
        ("Mobility MAE",mae_m, mae_m_interp),
    ]:
        print(f"   {label:<22} {gv:>15.4f} {ov:>15.4f}")
    print(f"──────────────────────────────────────────────\n")

    # save detailed results
    pd.DataFrame({
        "image_name" : interp_df["image_name"],
        "kappa_true" : interp_df["kappa"].values,
        "kappa_pred" : pred_k_interp,
        "kappa_err"  : np.abs(interp_df["kappa"].values - pred_k_interp),
        "mob_true"   : interp_df["mob"].values,
        "mob_pred"   : pred_m_interp,
        "mob_err"    : np.abs(interp_df["mob"].values - pred_m_interp),
    }).to_csv(os.path.join(SAVE_DIR, "interpolation_test_results.csv"), index=False)

    print("[INFO] Interpolation results saved.")

    parity_plot(
        interp_df["kappa"].values, pred_k_interp, 0, 11,
        f"kappa — Off-Grid (n={len(interp_df)})  |  R²={r2_k_interp:.3f}",
        os.path.join(SAVE_DIR, "parity_kappa_offgrid.png")
    )

    parity_plot(
        interp_df["mob"].values, pred_m_interp, 0, 11,
        f"M — Off-Grid (n={len(interp_df)})  |  R²={r2_m_interp:.3f}",
        os.path.join(SAVE_DIR, "parity_mob_offgrid.png")
    )

    print("[INFO] Off-grid parity plots saved.")

    # ------------------------------------------------------------------
    # 5.17  Done
    # ------------------------------------------------------------------
    elapsed = time.time() - t_start
    print(f"\n[INFO] Total runtime: {elapsed:.1f} s  ({elapsed/60:.1f} min)")
    print("[INFO] === DONE ===")
